### ISSUE TITLE
Mapping of UML associations (object-references) in YANG

### ISSUE THREAD

**Issue by XingZhao-CATR** [Open-Network-Models-and-Interfaces-ONMI/onmi-iisomi-uml-yang#2]
As agreed in ISSOMI call 3-28, the mapping guideline is:
![image](https://user-images.githubusercontent.com/24381130/38287223-1db86db2-37fc-11e8-8ad8-0a0a5cec1bab.png)
![image](https://user-images.githubusercontent.com/24381130/38287241-3607d74a-37fc-11e8-8387-2a5db1057aaf.png)

I didn't attend last week's ISSOMI call because of business travel. I still didn't understand the meaning of adding multiple leafrefs? For example, class-1-uuid refers to uuid in class-1 which already exists in class-1, why refer to each other?

**Comment by bzeuner** [comment]
Hallo Xing,
The issue is that a leafref can only locally reference an instance; e.g., in the example above, a leafref can reference Class3 from Class2 but not Class3 from Class5.
In order to reference Class3 from Class5 you **need multiple leafrefs**; one for Class1, one for Class2 and one for Class3. In the example above, the grouping class-3-ref defines these three leafrefs.

I will add the following text to the mapping guidelines (**please check**):
"_References in YANG can be expressed by leafref or instance-identifier built-in types. The reference to the RDN of a local class is mapped using a single leafref. The reference to the DN of a global class is mapped using multiple leafrefs (instance-identifier is not used).
Multiple leafrefs for references to global object instances are defined by the mapping tool in separate groupings. Those reference groupings are contained in the “definition of references” section of the YANG module. The mapping tool needs to define reference groupings for all classes that have at least one attribute identified as partOfObjectKey; see example mapping in Table 5.14 below._"
