### ISSUE TITLE
bits Modelling and Mapping

### ISSUE THREAD

**Issue by bzeuner** [Open-Network-Models-and-Interfaces-ONMI/onmi-iisomi-uml-yang#4]
The current "bits" modeling and mapping has two issues:

![bitsmapping](https://user-images.githubusercontent.com/6310277/42367129-703b7494-8103-11e8-8424-72472a20c4b5.png)

1. It is not possible to define a separate data type that can be used by many attributes.
2. OpenInterfaceModelAttribute::bitsDefinition does not allow to add a description.

**Proposed solution:**
1. Define a new Primitive Type Bits
2. Remove defaultValue from BitsDefinition
3. Add optional description to BitsDefinition
![bitdefinition](https://user-images.githubusercontent.com/6310277/42368987-e1a737bc-8108-11e8-8a96-abdb12be7cd0.png)
4. Remove BITS from Encoding
![encoding](https://user-images.githubusercontent.com/6310277/42369115-3c4fb75c-8109-11e8-911c-3862aad22187.png)

The usage would then be as follows:
![bitsusingclass](https://user-images.githubusercontent.com/6310277/42369184-78b6fcb4-8109-11e8-902f-5bcf3d6a1e29.png)

**Question:**
The YANG bit statement has in addition if-feature, reference and status. Should we also add these properties to the BitsDefinition?

What do you think?

**Comment by samans** [comment]
All information is available in either solution.  Depends on whether you want all the information stored in the attributes of a stereotype, or if you want explicit datatypes created that can be shown on a class diagram.  The tooling will not care, since it is just a matter of the tool understanding where to get the information that will be generated for YANG.

For Bernd's option:  I would want to be able to see the values of the attributes for the stereotype on the class diagram.  Also, I am not a fan of having an attribute called "defaultValue" when we should use OCL for such things.  If we don't care about OCL, then the tool just needs to know how to map the defaultValue to the default value syntax of the target language.
